#!/bin/sh

set -e

help="git-at <commit-ish> <file|filepath|relative filepath>\n"

[ -z "$1" ] || [ -z "$2" ] && {
	printf "$help"
	exit 1
}

time="$1"
file="$2"
shift
shift

repo_path="$(git rev-parse --show-toplevel)"
repo_name="$(basename "$repo_path")"

# need a relative path
# because git does not want an absolute one
#
# note that --relative-to is NOT posix.
#
filepath="$(realpath --relative-to="$repo_path" "$file")"

ago_dir="/tmp/git-at"
mkdir -p "$ago_dir"

filebase="$(basename "$file")"
#outfilepath="$ago_dir/$time:$filebase"
dirpath=$(dirname "$filepath")
outfilepath="$ago_dir/$repo_name/$dirpath/$time:$filebase"
mkdir -p "$(dirname "$outfilepath")"

/usr/bin/env git -c core.pager="cat" show "$time:$filepath" > "$outfilepath"

$EDITOR "$outfilepath"

